#!/bin/bash

# Define times for daily server wake-up

monday="20:00"
tuesday="20:00"
wednesday="20:00"
thursday="20:00"
friday="20:00"
saturday="20:00"
sunday="15:00"

weekday=$(date +%u)

case "$weekday" in
1) boot_time="$monday" ; next_boot_time="$tuesday"
;;
2) boot_time="$tuesday" ; next_boot_time="$wednesday"
;;
3) boot_time="$wednesday" ; next_boot_time="$thursday"
;;
4) boot_time="$thursday" ; next_boot_time="$friday"
;;
5) boot_time="$friday" ; next_boot_time="$saturday"
;;
6) boot_time="$saturday" ; next_boot_time="$sunday"
;;
7) boot_time="$sunday" ; next_boot_time="$monday"
;;
esac

compare_now=$(date +%H%M)
compare_boot_time=${boot_time:0:2}${boot_time:3:2}

if [ "$compare_now" -ge "$compare_boot_time" ]
then
rtcwake -m no -u -t $(date +%s -d 'tomorrow '$next_boot_time'')
else
rtcwake -m no -u -t $(date +%s -d 'today '$boot_time'')
at -f /home/tobias/.aufwecken $boot_time
fi

cat /proc/driver/rtc
echo "##############################"
