#!/bin/bash

# Weckzeiten festlegen
montag="20:00"
dienstag="20:00"
mittwoch="20:00"
donnerstag="20:00"
freitag="20:00"
samstag="20:00"
sonntag="15:00"

wochentag=$(date +%u)

case "$wochentag" in
1) weckzeit="$montag" ; nextweckzeit="$dienstag"
;;
2) weckzeit="$dienstag" ; nextweckzeit="$mittwoch"
;;
3) weckzeit="$mittwoch" ; nextweckzeit="$donnerstag"
;;
4) weckzeit="$donnerstag" ; nextweckzeit="$freitag"
;;
5) weckzeit="$freitag" ; nextweckzeit="$samstag"
;;
6) weckzeit="$samstag" ; nextweckzeit="$sonntag"
;;
7) weckzeit="$sonntag" ; nextweckzeit="$montag"
;;
esac

vergleich_jetzt=$(date +%H%M)
vergleich_weckzeit=${weckzeit:0:2}${weckzeit:3:2}

if [ "$vergleich_jetzt" -ge "$vergleich_weckzeit" ]
then
rtcwake -m no -u -t $(date +%s -d 'tomorrow '$nextweckzeit'')
else
rtcwake -m no -u -t $(date +%s -d 'today '$weckzeit'')
at -f /home/tobias/.aufwecken $weckzeit
fi

cat /proc/driver/rtc
echo "##############################"
